[mysqld]
# set basedir to your installation path
basedir=/usr/local/mysql
# set datadir to the location of your data directory
datadir=/usr/local/mysql/data
tmpdir=/usr/local/mysql/data/tmp
port=3306
# dodać do wywołania mysql --secure-file-priv= --binlog-ignore-db=testdb 

#innoDB coer
innodb_buffer_pool_size=20G
innodb_buffer_pool_instances=8

innodb_log_buffer_size=128M
innodb_sort_buffer_size=16M
innodb_flush_log_at_trx_commit=0

innodb_adaptive_hash_index = OFF  

innodb_buffer_pool_load_at_startup = OFF  
innodb_buffer_pool_dump_at_shutdown = OFF 


#io
innodb_io_capacity=10000
innodb_io_capacity_max=20000
innodb_read_io_threads=9
innodb_write_io_threads=9

#buffers
join_buffer_size=2M
sort_buffer_size=2M
read_buffer_size=2M
read_rnd_buffer_size=16M
bulk_insert_buffer_size=16M


#tmptables
tmp_table_size=512M
max_heap_table_size=512M



#connections
max_connections=100


#loading
loose-local-infile=1


#pockets
max_allowed_packet=4G


query_prealloc_size=512K 
log_bin=OFF
sync_binlog=0
innodb_log_file_size=5G
innodb_redo_log_capacity=5G

autocommit=0