{
 "title": "LogStructure",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "DMBS - Podstawowe informacjie",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(mysql_global_status_queries{job=\"summary\"}[$interval]) or irate(mysql_global_status_queries{job=\"summary\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DBS włączony od:",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_uptime{job=\"summary\"}",
       "legendFormat": "DBMS włączony od"
      }
     ]
    },
    {
     "title": "Bufor Mysql",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(mysql_global_variables_innodb_buffer_pool_size{job=\"summary\"})",
       "legendFormat": "Rozmiar bufora innoDB"
      },
      {
       "expr": "(windows_os_visible_memory_bytes{job=\"windows\"} - mysql_global_variables_innodb_buffer_pool_size{job=\"mysql\"})/1024^3",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Procent Zajętości Ram przez Bufor",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(mysql_global_variables_innodb_buffer_pool_size{job=\"summary\"} * 100) /  scalar(windows_os_visible_memory_bytes{job=\"summary\"})",
       "legendFormat": "Procentowo Bufor do ram"
      }
     ]
    }
   ]
  },
  {
   "title": "DBMS - Połączenia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Połączenia",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 192 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_variables_max_connections{job=\"summary\"}",
       "legendFormat": "Maxymalna liczba możliwych połączeń"
      },
      {
       "expr": "mysql_global_status_max_used_connections{job=\"summary\"}",
       "legendFormat": "Historycznie najwięcej użytych połączeń ostatniej sesji"
      },
      {
       "expr": "max(max_over_time(mysql_global_status_threads_connected{job=\"summary\"}[1s])  or mysql_global_status_threads_connected{job=\"summary\"} )",
       "legendFormat": "Aktualnie połączonych"
      }
     ]
    },
    {
     "title": "Połączenia",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 198 },
     "targets": [
      {
       "expr": "mysql_global_variables_max_connections{job=\"summary\"}",
       "legendFormat": "Maxymalna liczba możliwych połączeń"
      },
      {
       "expr": "max_over_time(mysql_global_status_threads_connected{job=\"summary\"}[$interval]) or\r\nmax_over_time(mysql_global_status_threads_connected{job=\"summary\"}[5m])",
       "legendFormat": " Maxymalna liczba otwartych połączeń: $interval "
      },
      {
       "expr": "max_over_time(mysql_global_status_threads_connected{job=\"summary\"}[1d])",
       "legendFormat": " Maxymalna liczba otwartych połączeń: 1d"
      },
      {
       "expr": "mysql_global_status_threads_connected{job=\"summary\"}",
       "legendFormat": "Liczba połączeń aktualnie"
      },
      {
       "expr": "rate(mysql_global_status_aborted_connects{job=\"summary\"}[$interval]) or irate(mysql_global_status_aborted_connects{job=\"summary\"}[5m])",
       "legendFormat": "Liczba porzuconych połączeń -  $interval"
      },
      {
       "expr": "rate(mysql_global_status_aborted_clients{job=\"summary\"}[$interval]) or irate(mysql_global_status_aborted_clients{job=\"summary\"}[5m])",
       "legendFormat": "Liczba porzuconych klientów -  $interval"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 206 },
     "targets": [
      {
       "expr": "mysql_global_variables_max_connections{job=\"summary\"}",
       "legendFormat": "Maxymalna liczba możliwych połączeń"
      },
      {
       "expr": "mysql_global_status_threads_running{job=\"summary\"}",
       "legendFormat": "Aktualnie działające wątki"
      },
      {
       "expr": "max_over_time(mysql_global_status_threads_running{job=\"summary\"}[$interval]) or\r\nmax_over_time(mysql_global_status_threads_running{job=\"summary\"}[5m])",
       "legendFormat": "Maxymalna liczba pracujących wątków  - $interval lub 5m"
      },
      {
       "expr": "max_over_time(mysql_global_status_threads_running{job=\"summary\"}[1d]) ",
       "legendFormat": "Maxymalna liczba pracujących wątków -1d"
      },
      {
       "expr": "avg_over_time(mysql_global_status_threads_running{job=\"summary\"}[$interval]) or\r\navg_over_time(mysql_global_status_threads_running{job=\"summary\"}[5m])",
       "legendFormat": "Średnia liczba pracujących wątków  - $interval lub 5m"
      },
      {
       "expr": "max_over_time(mysql_global_status_threads_running{job=\"summary\"}[1d]) ",
       "legendFormat": "Średnia liczba pracujących wątków -1d"
      },
      {
       "expr": "mysql_global_status_threads_cached{job=\"summary\"}",
       "legendFormat": "Wątki znajdujące się w uśpieniu"
      },
      {
       "expr": "max_over_time(mysql_global_status_threads_cached{job=\"summary\"}[$interval]) or\r\nmax_over_time(mysql_global_status_threads_cached{job=\"summary\"}[5m])",
       "legendFormat": "Maxymalna liczba uśpionych wątków  - $interval lub 5m"
      },
      {
       "expr": "max_over_time(mysql_global_status_threads_cached{job=\"summary\"}[1d])",
       "legendFormat": "Maxymalna liczba uśpionych wątków  - 1d"
      },
      {
       "expr": "avg_over_time(mysql_global_status_threads_cached{job=\"summary\"}[$interval]) or\r\navg_over_time(mysql_global_status_threads_cached{job=\"summary\"}[5m])",
       "legendFormat": "Średnia liczba uśpionych wątków  - $interval lub 5m"
      },
      {
       "expr": "avg_over_time(mysql_global_status_threads_cached{job=\"summary\"}[1d])",
       "legendFormat": "Średnia liczba uśpionych wątków  - 1d"
      }
     ]
    }
   ]
  },
  {
   "title": "DBMS - Użycie sieci",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Użycie sieci",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(mysql_global_status_bytes_received{job=\"summary\"}[$interval]) or irate(mysql_global_status_bytes_received{job=\"summary\"}[5m])",
       "legendFormat": "Przepustowość przychodząca"
      },
      {
       "expr": "rate(mysql_global_status_bytes_sent{job=\"summary\"}[$interval]) or irate(mysql_global_status_bytes_sent{job=\"summary\"}[5m])",
       "legendFormat": "Przepustowość wychodząca"
      }
     ]
    },
    {
     "title": "Ogólne użycie sieci ostatnie 24h",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(mysql_global_status_bytes_received{job=\"summary\"}[1h])",
       "legendFormat": "Odebrano"
      },
      {
       "expr": "increase(mysql_global_status_bytes_sent{job=\"summary\"}[1h])",
       "legendFormat": "Wysłano"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zużycie CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{job=\"summary\",mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "Całkowite użycie procesora"
      },
      {
       "expr": "(avg by (instance) (rate(windows_cpu_time_total{job=\"summary\",mode=\"user\"}[1m])) * 100)",
       "legendFormat": "Użycie dla trybu użytkownik"
      },
      {
       "expr": "(avg by (instance) (rate(windows_cpu_time_total{job=\"summary\",mode=\"dpc\"}[1m])) * 100)",
       "legendFormat": "Użycie dla trybu dpc"
      },
      {
       "expr": "(avg by (instance) (rate(windows_cpu_time_total{job=\"summary\",mode=\"interrupt\"}[1m])) * 100)",
       "legendFormat": "Użycie dla trybu interrupt"
      },
      {
       "expr": "(avg by (instance) (rate(windows_cpu_time_total{job=\"summary\",mode=\"privileged\"}[1m])) * 100)",
       "legendFormat": "Użycie dla trybu privileged"
      }
     ]
    }
   ]
  },
  {
   "title": "Ram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zużycie Ram - Windows 10",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "(windows_os_visible_memory_bytes{job=\"summary\"})/1024^3",
       "legendFormat": "Zainstalowana pamięć RAM:"
      },
      {
       "expr": "(windows_os_visible_memory_bytes{job=\"summary\"} - windows_memory_available_bytes{job=\"summary\"}) /1024^3",
       "legendFormat": "Pamięć RAM w użyciu: "
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Dyski",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prędkość operacji Na dysku - odczyt",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(windows_physical_disk_read_bytes_total{job=\"summary\", disk=\"3\"}[$__interval]) or rate(windows_physical_disk_read_bytes_total{job=\"summary\", disk=\"3\"}[5m])",
       "legendFormat": "Dysk C - Serwer Disc"
      },
      {
       "expr": "rate(windows_physical_disk_read_bytes_total{job=\"summary\", disk=\"2\"}[$__interval]) or rate(windows_physical_disk_read_bytes_total{job=\"summary\", disk=\"2\"}[5m])",
       "legendFormat": "Dysk F - Data Disc"
      }
     ]
    },
    {
     "title": "Latency dla dysków - zapis",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_write_latency_seconds_total{job=\"summary\",volume=\"C:\"}[$__interval]) or rate(windows_logical_disk_write_latency_seconds_total{job=\"summary\",volume=\"C:\"}[5m])",
       "legendFormat": "Dysk C - Serwer disc"
      },
      {
       "expr": "rate(windows_logical_disk_write_latency_seconds_total{job=\"summary\",volume=\"F:\"}[$__interval]) or rate(windows_logical_disk_write_latency_seconds_total{job=\"summary\",volume=\"F:\"}[5m])",
       "legendFormat": "Dysk F - Data disc"
      }
     ]
    },
    {
     "title": "Liczba operacji - zapis",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 25 },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_writes_total{job=\"summary\",volume=\"C:\"}[$__interval]) or rate(windows_logical_disk_writes_total{job=\"summary\",volume=\"C:\"}[5m])",
       "legendFormat": "Dysk C - Serwer disc"
      },
      {
       "expr": "rate(windows_logical_writes_reads_total{job=\"summary\",volume=\"F:\"}[$__interval]) or rate(windows_logical_disk_writes_total{job=\"summary\",volume=\"F:\"}[5m])",
       "legendFormat": "Dysk F - Data disc"
      }
     ]
    },
    {
     "title": "Prędkość operacji Na dysku - zapis",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(windows_physical_disk_write_bytes_total{job=\"summary\", disk=\"3\"}[$__interval]) or rate(windows_physical_disk_write_bytes_total{job=\"summary\", disk=\"3\"}[5m])",
       "legendFormat": "Dysk C - Serwer Disc"
      },
      {
       "expr": "rate(windows_physical_disk_write_bytes_total{job=\"summary\", disk=\"2\"}[$__interval]) or rate(windows_physical_disk_write_bytes_total{job=\"summary\", disk=\"2\"}[5m])",
       "legendFormat": "Dysk F - Data Disk"
      }
     ]
    },
    {
     "title": "Latency dla dysków - odczyt",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_read_latency_seconds_total{job=\"summary\",volume=\"C:\"}[$__interval]) or rate(windows_logical_disk_read_latency_seconds_total{job=\"summary\",volume=\"C:\"}[5m])",
       "legendFormat": "Dysk C - serwer disc"
      },
      {
       "expr": "rate(windows_logical_disk_read_latency_seconds_total{job=\"summary\",volume=\"F:\"}[$__interval]) or rate(windows_logical_disk_read_latency_seconds_total{job=\"summary\",volume=\"F:\"}[5m])",
       "legendFormat": "Dysk F - Data disc"
      }
     ]
    },
    {
     "title": "Liczba operacji - odczyt",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 39 },
     "targets": [
      {
       "expr": "rate(windows_logical_disk_reads_total{job=\"summary\",volume=\"C:\"}[$__interval]) or rate(windows_logical_disk_reads_total{job=\"summary\",volume=\"C:\"}[5m])",
       "legendFormat": "Dysk C - Serwer disc"
      },
      {
       "expr": "rate(windows_logical_disk_reads_total{job=\"summary\",volume=\"F:\"}[$__interval]) or rate(windows_logical_disk_reads_total{job=\"summary\",volume=\"F:\"}[5m])",
       "legendFormat": "Dysk F - Data disc"
      }
     ]
    }
   ]
  }
 ]
}