[mysqld]
# set basedir to your installation path
basedir=/usr/local/mysql
# set datadir to the location of your data directory
datadir=/usr/local/mysql/data
tmpdir=/usr/local/mysql/data/tmp
port=3306

# InnoDB core
innodb_buffer_pool_size=17G
innodb_buffer_pool_instances=8

innodb_log_buffer_size=128M
innodb_redo_log_capacity=2G

innodb_flush_log_at_trx_commit=0
sync_binlog=0

innodb_adaptive_hash_index=ON

# IO
innodb_io_capacity=2000
innodb_io_capacity_max=4000
innodb_read_io_threads=4
innodb_write_io_threads=4

# buffers (per-thread!)
join_buffer_size=512K
sort_buffer_size=1M
read_buffer_size=1M
read_rnd_buffer_size=2M

# temp tables
tmp_table_size=128M
max_heap_table_size=128M

# cache
table_open_cache=4000
table_definition_cache=2000

# connections
max_connections=10000

# loading
loose-local-infile=1

# packet
max_allowed_packet=256M