package selectqueries

var SelectQueriesStack = map[string]*[]string{
	//postqueries
	"idselcectPost":                 &idselcectPost,
	"idselcectPostLimit":            &idselcectPostLimit,
	"postTypeselcectPost":           &postTypeselcectPost,
	"postTypeselcectPostLimit":      &postTypeselcectPostLimit,
	"accepdedansweridcectPost":      &accepdedansweridcectPost,
	"accepdedansweridcectPostLimit": &accepdedansweridcectPostLimit,
	"parentIDselectPost":            &parentIDselectPost,
	"creationDateSelectPost":        &creationDateSelectPost,
	"scoreSelectPost":               &scoreSelectPost,
	"viewCountSelectPost":           &viewCountSelectPost,
	"postBodySelectPost":            &postBodySelectPost,
	"ownerUserIDSelectPost":         &ownerUserIDSelectPost,
	"lastEditorUserIDSelectPost":    &lastEditorUserIDSelectPost,
	"lastEditDateSelectPost":        &lastEditDateSelectPost,
	"lastActivityDateSelectPost":    &lastActivityDateSelectPost,
	"postTitleSelectPost":           &postTitleSelectPost,
	"tagsSelectPost":                &tagsSelectPost,
	"answerCountSelectPost":         &answerCountSelectPost,
	"commentCountSelectPost":        &commentCountSelectPost,
	"contentLicenseSelectPost":      &contentLicenseSelectPost,
	"multiConditionSelectPost":      &multiConditionSelectPost,
	"groupBySelectPost":             &groupBySelectPost,
	"orderBySelectPost":             &orderBySelectPost,
	"betweenSelectPost":             &betweenSelectPost,
	"fullScanSelectPost":            &fullScanSelectPost,
	"countSelectPost":               &countSelectPost,
	"analizeUserActivity":           &analizeUserActivity,
	"analizePostTags":               &analizePostTags,
	"analizePostDate":               &analizePostDate,
	"viewMarkAnalize":               &viewMarkAnalize,
	"answersComsAnalize":            &answersComsAnalize,
	"liceneAnalize":                 &liceneAnalize,
	"conditionsAnalize":             &conditionsAnalize,
	"agregatePostAnalize":           &agregatePostAnalize,
	"subQueryAnalize":               &subQueryAnalize,
	//full database tests
	"SELECTJOIN ":     &joinAnalize,
	"AgregateGroupBy": &agregateAnalize,
	"SubandCTE":       &subAndCteAnalize,
	"WindowTrend":     &funWinTrendAnalize,
	"Opt":             &optAnalize,
	"indexAnalize":    &indexAnalize,
	//raporty
	"usertRaports":       &usertRaports,
	"postRaport":         &postRaport,
	"commentRaport":      &commentRaport,
	"badgeRaport":        &badgeRaport,
	"voteRaport":         &voteRaport,
	"postHistoryRaport":  &postHistoryRaport,
	"advanceAnalize":     &advanceAnalize,
	"performacneAnalize": &performacneAnalize,
}
