package main

var Posts = []string{

	"SELECT p.id, p.post_title, p.score, p.view_count, p.answer_count, p.creation_date, u.id AS author_id,u.display_name, u.reputation FROM posts AS p LEFT JOIN users AS u ON u.id = p.owner_user_id WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.post_type_id = 1 ORDER BY p.score DESC, p.view_count DESC LIMIT 100;",
	// Q02. Pytania i zaakceptowane odpowiedzi; pruning tylko dla q
	"SELECT q.id AS question_id, q.post_title, q.score AS question_score, qu.display_name AS question_author, a.id AS answer_id, a.score AS answer_score, au.display_name AS answer_author FROM posts AS q JOIN posts AS a ON a.id = q.accepted_answer_id LEFT JOIN users AS qu ON qu.id = q.owner_user_id LEFT JOIN users AS au ON au.id = a.owner_user_id WHERE q.creation_date >= '2009-04-01' AND q.creation_date <  '2009-07-01' AND q.post_type_id = 1 AND q.accepted_answer_id IS NOT NULL ORDER BY q.score DESC LIMIT 100;",
	// Q03. Pytania i zaakceptowane odpowiedzi; pruning dla obu aliasów posts
	"SELECT q.id AS question_id, q.post_title, q.score AS question_score, qu.display_name AS question_author, a.id AS answer_id, a.score AS answer_score, au.display_name AS answer_author FROM posts AS q JOIN posts AS a ON a.id = q.accepted_answer_id LEFT JOIN users AS qu ON qu.id = q.owner_user_id LEFT JOIN users AS au ON au.id = a.owner_user_id WHERE q.creation_date >= '2009-04-01' AND q.creation_date <  '2009-07-01' AND a.creation_date >= '2009-04-01' AND a.creation_date <  '2009-07-01' AND q.post_type_id = 1 ORDER BY q.score DESC LIMIT 100; ",
	// Q04. Odpowiedzi i pytania nadrzędne; pruning tylko dla odpowiedzi
	"SELECT a.id AS answer_id, a.score AS answer_score, au.display_name AS answer_author, q.id AS question_id, q.post_title, q.score AS question_score, qu.display_name AS question_author FROM posts AS a JOIN posts AS q ON q.id = a.parent_id LEFT JOIN users AS au ON au.id = a.owner_user_id LEFT JOIN users AS qu ON qu.id = q.owner_user_id WHERE a.creation_date >= '2009-04-01' AND a.creation_date <  '2009-07-01' AND a.post_type_id = 2 ORDER BY a.score DESC LIMIT 100; ",
	// Q05. Odpowiedzi i pytania nadrzędne; pruning dla obu aliasów
	"SELECT a.id AS answer_id, a.score AS answer_score, au.display_name AS answer_author, q.id AS question_id, q.post_title, q.score AS question_score, qu.display_name AS question_author FROM posts AS a JOIN posts AS q ON q.id = a.parent_id LEFT JOIN users AS au  ON au.id = a.owner_user_id LEFT JOIN users AS qu ON qu.id = q.owner_user_id WHERE a.creation_date >= '2009-04-01' AND a.creation_date <  '2009-07-01' AND q.creation_date >= '2009-04-01' AND q.creation_date <  '2009-07-01' AND a.post_type_id = 2 ORDER BY a.score DESC LIMIT 100; ",
	//Q06. Ranking autorów pytań w kwartale
	"SELECT u.id, u.display_name, u.reputation, COUNT(*) AS question_count, SUM(p.score) AS total_score, AVG(p.view_count) AS avg_views, SUM(p.answer_count) AS total_answers FROM posts AS p JOIN users AS u ON u.id = p.owner_user_id WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.post_type_id = 1 GROUP BY u.id, u.display_name, u.reputation HAVING COUNT(*) >= 3 ORDER BY total_score DESC, question_count DESC LIMIT 100;",
	// Q07. Ranking autorów pytań w całym roku
	"SELECT u.id, u.display_name, u.reputation, COUNT(*) AS question_count, SUM(p.score) AS total_score, AVG(p.view_count) AS avg_views, SUM(p.answer_count) AS total_answers FROM posts AS p JOIN users AS u ON u.id = p.owner_user_id WHERE p.creation_date >= '2009-01-01' AND p.creation_date <  '2010-01-01' AND p.post_type_id = 1 GROUP BY u.id, u.display_name, u.reputation HAVING COUNT(*) >= 5 ORDER BY total_score DESC, question_count DESC LIMIT 100;",
	// Q08. Dzienne statystyki pytań i aktywnych autorów
	"SELECT DATE(p.creation_date) AS day, COUNT(*) AS question_count, COUNT(DISTINCT u.id) AS active_authors,  SUM(p.score) AS total_score, AVG(p.view_count) AS avg_views, SUM(p.answer_count) AS answer_count FROM posts AS p LEFT JOIN users AS u ON u.id = p.owner_user_id WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.post_type_id = 1 GROUP BY DATE(p.creation_date) ORDER BY day;",
	// Q09. Autor i ostatni edytor postu
	" SELECT p.id, p.post_title, p.post_type_id, p.score, p.creation_date, owner.display_name AS owner_name, editor.display_name AS editor_name, p.last_edit_date FROM posts AS p LEFT JOIN users AS owner ON owner.id = p.owner_user_id LEFT JOIN users AS editor ON editor.id = p.last_editor_user_id WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.last_editor_user_id IS NOT NULL ORDER BY p.last_edit_date DESC LIMIT 100; ",
	// Q10. Liczba pytań i odpowiedzi poszczególnych użytkowników
	"SELECT u.id, u.display_name, SUM(p.post_type_id = 1) AS question_count, SUM(p.post_type_id = 2) AS answer_count,  SUM(p.score) AS total_score, AVG(p.score) AS avg_score FROM users AS u JOIN posts AS p ON p.owner_user_id = u.id WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' GROUP BY u.id, u.display_name HAVING COUNT(*) >= 5 ORDER BY total_score DESC LIMIT 100; ",
	// Q11. Najlepsi autorzy każdego dnia z funkcją okienkową
	"WITH daily_author_stats AS ( SELECT DATE(p.creation_date) AS day, p.owner_user_id, COUNT(*) AS post_count, SUM(p.score) AS total_score FROM posts AS p WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.owner_user_id IS NOT NULL GROUP BY DATE(p.creation_date), p.owner_user_id ), ranked AS ( SELECT day, owner_user_id, post_count, total_score, DENSE_RANK() OVER ( PARTITION BY day ORDER BY total_score DESC ) AS score_rank FROM daily_author_stats) SELECT r.day, r.score_rank, u.id,u.display_name, r.post_count, r.total_score FROM ranked AS r JOIN users AS u ON u.id = r.owner_user_id WHERE r.score_rank <= 10 ORDER BY r.day, r.score_rank; ",
	// Q12. Ranking autorów w kwartale z funkcjami okienkowymi
	" WITH author_stats AS ( SELECT p.owner_user_id, COUNT(*) AS post_count, SUM(p.score) AS total_score, AVG(p.view_count) AS avg_views FROM posts AS p WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.owner_user_id IS NOT NULL GROUP BY p.owner_user_id ) SELECT u.id, u.display_name, a.post_count, a.total_score, a.avg_views, DENSE_RANK() OVER (ORDER BY a.total_score DESC) AS score_rank, DENSE_RANK() OVER (ORDER BY a.post_count DESC) AS activity_rank FROM author_stats AS a JOIN users AS u ON u.id = a.owner_user_id ORDER BY score_rank LIMIT 100; ",
	//Q13. Miesięczna aktywność autorów
	"SELECT YEAR(p.creation_date) AS year_number, MONTH(p.creation_date) AS month_number, u.id, u.display_name, COUNT(*) AS post_count, SUM(p.score) AS total_score FROM posts AS p JOIN users AS u ON u.id = p.owner_user_id WHERE p.creation_date >= '2009-01-01' AND p.creation_date <  '2010-01-01' GROUP BY YEAR(p.creation_date), MONTH(p.creation_date), u.id, u.display_name HAVING COUNT(*) >= 5 ORDER BY year_number, month_number, total_score DESC LIMIT 500; ",
	// Q14. Różnica wyniku pytania i zaakceptowanej odpowiedzi
	"SELECT q.id AS question_id,q.post_title,q.score AS question_score,a.id AS accepted_answer_id,a.score AS answer_score,a.score - q.score AS score_difference,  qu.display_name AS question_author, au.display_name AS answer_author FROM posts AS q JOIN posts AS a ON a.id = q.accepted_answer_id LEFT JOIN users AS qu ON qu.id = q.owner_user_id LEFT JOIN users AS au ON au.id = a.owner_user_id WHERE q.creation_date >= '2009-04-01' AND q.creation_date <  '2009-07-01' AND a.creation_date >= '2009-04-01' AND a.creation_date <  '2009-10-01' AND q.post_type_id = 1 ORDER BY score_difference DESC LIMIT 100; ",
	// Q15. Użytkownicy, których odpowiedzi zostały zaakceptowane
	"SELECT au.id, au.display_name, COUNT(*) AS accepted_answer_count, SUM(a.score) AS accepted_answer_score, AVG(a.score) AS avg_accepted_answer_score, COUNT(DISTINCT q.owner_user_id) AS distinct_question_authors FROM posts AS q JOIN posts AS a ON a.id = q.accepted_answer_id JOIN users AS au ON au.id = a.owner_user_id WHERE q.creation_date >= '2009-04-01' AND q.creation_date <  '2009-07-01' AND a.creation_date >= '2009-04-01' AND a.creation_date <  '2009-10-01' GROUP BY au.id, au.display_name HAVING COUNT(*) >= 2 ORDER BY accepted_answer_count DESC, accepted_answer_score DESC LIMIT 100; ",
	//Q16. Posty i statystyki komentarzy
	// Zapytanie cięższe: comments nie ma osobnego indeksu zaczynającego się od post_id.
	"WITH candidate_posts AS ( SELECT p.id, p.owner_user_id, p.post_title, p.score, p.comment_count FROM posts AS p WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.post_type_id = 1 ORDER BY p.score DESC LIMIT 1000 ), comment_stats AS ( SELECT c.post_id, COUNT(*) AS real_comment_count, COUNT(DISTINCT c.user_id) AS commenter_count, AVG(c.score) AS avg_comment_score, MAX(c.creation_date) AS last_comment_date FROM comments AS c JOIN candidate_posts AS cp ON cp.id = c.post_id GROUP BY c.post_id )SELECT cp.id, cp.post_title, cp.score, u.display_name, cp.comment_count AS stored_comment_count, cs.real_comment_count, cs.commenter_count, cs.avg_comment_score, cs.last_comment_date FROM candidate_posts AS cp LEFT JOIN comment_stats AS cs ON cs.post_id = cp.id LEFT JOIN users AS u ON u.id = cp.owner_user_id ORDER BY cs.real_comment_count DESC, cp.score DESC LIMIT 100; ",
	// Q17. Posty i statystyki głosów
	// Zapytanie cięższe: votes nie ma osobnego indeksu zaczynającego się od post_id.
	"WITH candidate_posts AS ( SELECT p.id, p.owner_user_id, p.post_title, p.score FROM posts AS p WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.post_type_id = 1 ORDER BY p.score DESC LIMIT 1000 ), vote_stats AS ( SELECT v.post_id, COUNT(*) AS vote_count, SUM(v.vote_type_id = 2) AS type_2_votes, SUM(v.vote_type_id = 3) AS type_3_votes, COUNT(DISTINCT v.vote_type_id) AS vote_type_count FROM votes AS v JOIN candidate_posts AS cp ON cp.id = v.post_id GROUP BY v.post_id ) SELECT cp.id, cp.post_title, cp.score, u.display_name, vs.vote_count, vs.type_2_votes, vs.type_3_votes, vs.vote_type_count FROM candidate_posts AS cp LEFT JOIN vote_stats AS vs ON vs.post_id = cp.id LEFT JOIN users AS u ON u.id = cp.owner_user_id ORDER BY vs.vote_count DESC, cp.score DESC LIMIT 100; ",
	//Q18. Posty i liczba zmian w historii
	// Zapytanie cięższe: post_history nie ma osobnego indeksu zaczynającego się od post_id.
	"WITH candidate_posts AS ( SELECT p.id, p.owner_user_id, p.post_title, p.score FROM posts AS p WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND p.post_type_id = 1 ORDER BY p.score DESC LIMIT 1000 ), history_stats AS ( SELECT ph.post_id, COUNT(*) AS revision_count, COUNT(DISTINCT ph.user_id) AS editor_count, COUNT(DISTINCT ph.post_history_type_id) AS history_type_count, MAX(ph.creation_date) AS last_revision FROM post_history AS ph JOIN candidate_posts AS cp ON cp.id = ph.post_id GROUP BY ph.post_id ) SELECT cp.id, cp.post_title,cp.score, u.display_name, hs.revision_count, hs.editor_count, hs.history_type_count, hs.last_revision FROM candidate_posts AS cp LEFT JOIN history_stats AS hs ON hs.post_id = cp.id LEFT JOIN users AS u ON u.id = cp.owner_user_id ORDER BY hs.revision_count DESC, cp.score DESC LIMIT 100; ",
	//Q19. Powiązane posty, z filtrem daty dla obu aliasów posts
	// Zapytanie cięższe: post_links nie ma indeksów po post_id i related_post_id.
	" SELECT pl.id AS link_id, pl.link_type_id, pl.creation_date AS link_date, p.id AS source_post_id, p.post_title AS source_title, pu.display_name AS source_author, rp.id AS related_post_id, rp.post_title AS related_title, rpu.display_name AS related_author FROM posts AS p JOIN post_links AS pl ON pl.post_id = p.id JOIN posts AS rp ON rp.id = pl.related_post_id LEFT JOIN users AS pu ON pu.id = p.owner_user_id LEFT JOIN users AS rpu ON rpu.id = rp.owner_user_id WHERE p.creation_date >= '2009-04-01' AND p.creation_date <  '2009-07-01' AND rp.creation_date >= '2009-04-01' AND rp.creation_date <  '2009-10-01' ORDER BY pl.creation_date DESC LIMIT 100; ",
	//Q20. Zapytanie kontrolne bez predykatu po creation_date
	// Tabela partycjonowana nie może tu efektywnie przyciąć partycji posts.
	"SELECT u.id, u.display_name, u.reputation, COUNT(*) AS question_count, SUM(p.score) AS total_score, AVG(p.view_count) AS avg_views FROM posts AS p JOIN users AS u ON u.id = p.owner_user_id WHERE p.post_type_id = 1 AND p.score >= 10 GROUP BY u.id, u.display_name, u.reputation HAVING COUNT(*) >= 3 ORDER BY total_score DESC LIMIT 100;",
}

var users = []string{
	// Q01: Jeden użytkownik z niskiego zakresu identyfikatorów
	"SELECT u.id,u.display_name,u.reputation,COUNT(p.id) AS post_count,SUM(CASE WHEN p.post_type_id=1 THEN 1 ELSE 0 END) AS question_count,SUM(CASE WHEN p.post_type_id=2 THEN 1 ELSE 0 END) AS answer_count,COALESCE(SUM(p.score),0) AS total_score FROM users u LEFT JOIN posts p ON p.owner_user_id=u.id WHERE u.id=496624 GROUP BY u.id,u.display_name,u.reputation;",
	// Q02: Jeden użytkownik ze średniego zakresu identyfikatorów
	"SELECT u.id,u.display_name,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.post_id) AS commented_posts,COALESCE(SUM(c.score),0) AS comment_score FROM users u LEFT JOIN comments c ON c.user_id=u.id WHERE u.id=827420 GROUP BY u.id,u.display_name;",
	// Q03: Jeden użytkownik ze średnio-wysokiego zakresu identyfikatorów
	"SELECT u.id,u.display_name,b.class,COUNT(b.id) AS badge_count,MIN(b.badge_date) AS first_badge,MAX(b.badge_date) AS last_badge FROM users u LEFT JOIN badges b ON b.user_id=u.id WHERE u.id=5123459 GROUP BY u.id,u.display_name,b.class ORDER BY b.class;",
	// Q04: Jeden użytkownik z wysokiego zakresu identyfikatorów
	"SELECT u.id,u.display_name,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.post_id) AS edited_posts,COUNT(DISTINCT ph.post_history_type_id) AS history_type_count,MAX(ph.creation_date) AS last_revision FROM users u LEFT JOIN post_history ph ON ph.user_id=u.id WHERE u.id=8000123 GROUP BY u.id,u.display_name;",
	// Q05: Jeden użytkownik jako właściciel i ostatni edytor postów
	"WITH owned_stats AS (SELECT owner_user_id,COUNT(*) AS owned_posts,SUM(score) AS owned_score FROM posts WHERE owner_user_id=9800001 GROUP BY owner_user_id),edited_stats AS (SELECT last_editor_user_id,COUNT(*) AS last_edited_posts FROM posts WHERE last_editor_user_id=9800001 GROUP BY last_editor_user_id) SELECT u.id,u.display_name,COALESCE(os.owned_posts,0) AS owned_posts,COALESCE(es.last_edited_posts,0) AS last_edited_posts,COALESCE(os.owned_score,0) AS owned_score FROM users u LEFT JOIN owned_stats os ON os.owner_user_id=u.id LEFT JOIN edited_stats es ON es.last_editor_user_id=u.id WHERE u.id=9800001;",
	// Q06: Identyfikatory z jednej partycji HASH: każdy MOD(id,4)=1
	"SELECT u.id,u.display_name,u.reputation,COUNT(p.id) AS post_count,COALESCE(SUM(p.score),0) AS total_score FROM users u LEFT JOIN posts p ON p.owner_user_id=u.id WHERE u.id IN (100001,1500001,5100001,9000001) GROUP BY u.id,u.display_name,u.reputation ORDER BY u.id;",
	// Q07: Identyfikatory rozłożone na cztery partycje HASH
	"SELECT u.id,u.display_name,u.reputation,COUNT(p.id) AS post_count,COALESCE(SUM(p.score),0) AS total_score FROM users u LEFT JOIN posts p ON p.owner_user_id=u.id WHERE u.id IN (100001,1500002,5100003,9000004) GROUP BY u.id,u.display_name,u.reputation ORDER BY u.id;",
	// Q08: Większa lista identyfikatorów z jednej partycji HASH: każdy MOD(id,4)=1
	"SELECT u.id,u.display_name,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.post_id) AS commented_posts FROM users u LEFT JOIN comments c ON c.user_id=u.id WHERE u.id IN (100001,650001,1500001,3200001,5100001,7000001,8500001,9800001) GROUP BY u.id,u.display_name ORDER BY comment_count DESC;",
	// Q09: Większa lista identyfikatorów rozłożona równomiernie na cztery partycje HASH
	"SELECT u.id,u.display_name,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.post_id) AS commented_posts FROM users u LEFT JOIN comments c ON c.user_id=u.id WHERE u.id IN (100001,650002,1500003,3200004,5100005,7000006,8500007,9800008) GROUP BY u.id,u.display_name ORDER BY comment_count DESC;",
	// Q10: Zakres identyfikatorów ze środkowej części tabeli, bez skutecznego pruningu HASH
	"SELECT u.id,u.display_name,u.reputation,COUNT(p.id) AS post_count,COALESCE(SUM(p.score),0) AS total_score FROM users u LEFT JOIN posts p ON p.owner_user_id=u.id WHERE u.id>=5000000 AND u.id<5100000 GROUP BY u.id,u.display_name,u.reputation ORDER BY total_score DESC LIMIT 100;",
	// Q11: Filtrowanie po reputacji bez warunku po kluczu partycjonowania
	"SELECT u.id,u.display_name,u.reputation,COUNT(p.id) AS post_count,AVG(p.score) AS avg_post_score,COALESCE(SUM(p.view_count),0) AS total_views FROM users u LEFT JOIN posts p ON p.owner_user_id=u.id WHERE u.reputation>=10000 GROUP BY u.id,u.display_name,u.reputation ORDER BY u.reputation DESC LIMIT 100;",
	// Q12: Filtrowanie użytkowników po dacie utworzenia bez warunku po id
	"SELECT u.id,u.display_name,u.creation_date,COUNT(p.id) AS post_count,COALESCE(SUM(p.score),0) AS total_score FROM users u LEFT JOIN posts p ON p.owner_user_id=u.id WHERE u.creation_date>='2009-01-01' AND u.creation_date<'2010-01-01' GROUP BY u.id,u.display_name,u.creation_date ORDER BY total_score DESC LIMIT 100;",
	// Q13: Ranking autorów pytań w kwartale
	"SELECT u.id,u.display_name,u.reputation,COUNT(p.id) AS question_count,COALESCE(SUM(p.score),0) AS total_score,AVG(p.view_count) AS avg_views FROM posts p JOIN users u ON u.id=p.owner_user_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' AND p.post_type_id=1 GROUP BY u.id,u.display_name,u.reputation HAVING COUNT(p.id)>=3 ORDER BY total_score DESC LIMIT 100;",
	// Q14: Ranking autorów odpowiedzi w kwartale
	"SELECT u.id,u.display_name,u.reputation,COUNT(p.id) AS answer_count,COALESCE(SUM(p.score),0) AS total_answer_score,AVG(p.score) AS avg_answer_score FROM posts p JOIN users u ON u.id=p.owner_user_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' AND p.post_type_id=2 GROUP BY u.id,u.display_name,u.reputation HAVING COUNT(p.id)>=3 ORDER BY total_answer_score DESC LIMIT 100;",
	// Q15: Użytkownicy komentujący pytania z wybranego kwartału
	"SELECT u.id,u.display_name,COUNT(c.id) AS comment_count,COUNT(DISTINCT p.id) AS commented_questions,COALESCE(SUM(c.score),0) AS total_comment_score FROM posts p JOIN comments c ON c.post_id=p.id JOIN users u ON u.id=c.user_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' AND p.post_type_id=1 GROUP BY u.id,u.display_name ORDER BY comment_count DESC LIMIT 100;",
	// Q16: Autor zaakceptowanych odpowiedzi z wysokiego zakresu identyfikatorów
	"SELECT q.id AS question_id,q.post_title,qu.id AS question_author_id,qu.display_name AS question_author,a.id AS answer_id,au.id AS answer_author_id,au.display_name AS answer_author,a.score AS answer_score FROM posts q JOIN posts a ON a.id=q.accepted_answer_id LEFT JOIN users qu ON qu.id=q.owner_user_id LEFT JOIN users au ON au.id=a.owner_user_id WHERE au.id=49 AND q.creation_date>='2009-01-01' AND q.creation_date<'2010-01-01' ORDER BY a.score DESC LIMIT 100;",
	// Q17: Autorzy pytań z jednej partycji oraz autorzy odpowiedzi z czterech partycji
	"SELECT q.id AS question_id,q.post_title,qu.id AS question_author_id,qu.display_name AS question_author,a.id AS answer_id,au.id AS answer_author_id,au.display_name AS answer_author FROM posts q JOIN posts a ON a.parent_id=q.id JOIN users qu ON qu.id=q.owner_user_id JOIN users au ON au.id=a.owner_user_id WHERE qu.id IN (2417600,5562701,2315276,1604377,3452342) AND au.id IN (4363956,2976522,6977241,1733235,3319513) AND q.creation_date>='2009-04-01' AND q.creation_date<'2009-07-01' LIMIT 100;",
	// Q18: CTE z użytkownikami z jednej partycji HASH
	"WITH selected_users AS (SELECT id,display_name,reputation FROM users WHERE id IN (100001,650001,1500001,3200001,5100001,7000001,8500001,9800001)),post_stats AS (SELECT p.owner_user_id,COUNT(*) AS post_count,SUM(p.score) AS total_score,AVG(p.view_count) AS avg_views FROM posts p JOIN selected_users su ON su.id=p.owner_user_id WHERE p.creation_date>='2009-01-01' AND p.creation_date<'2010-01-01' GROUP BY p.owner_user_id) SELECT su.id,su.display_name,su.reputation,COALESCE(ps.post_count,0) AS post_count,COALESCE(ps.total_score,0) AS total_score,ps.avg_views FROM selected_users su LEFT JOIN post_stats ps ON ps.owner_user_id=su.id ORDER BY total_score DESC;",
	// Q19: CTE z użytkownikami rozłożonymi na wszystkie partycje HASH
	"WITH selected_users AS (SELECT id,display_name,reputation FROM users WHERE id IN (100001,650002,1500003,3200004,5100005,7000006,8500007,9800008)),post_stats AS (SELECT p.owner_user_id,COUNT(*) AS post_count,SUM(p.score) AS total_score FROM posts p JOIN selected_users su ON su.id=p.owner_user_id GROUP BY p.owner_user_id),comment_stats AS (SELECT c.user_id,COUNT(*) AS comment_count,SUM(c.score) AS comment_score FROM comments c JOIN selected_users su ON su.id=c.user_id GROUP BY c.user_id) SELECT su.id,su.display_name,su.reputation,COALESCE(ps.post_count,0) AS post_count,COALESCE(ps.total_score,0) AS total_score,COALESCE(cs.comment_count,0) AS comment_count,COALESCE(cs.comment_score,0) AS comment_score FROM selected_users su LEFT JOIN post_stats ps ON ps.owner_user_id=su.id LEFT JOIN comment_stats cs ON cs.user_id=su.id ORDER BY total_score DESC,comment_count DESC;",
	// Q20: Funkcje okienkowe bez ograniczenia po id, przypadek kontrolny
	"WITH user_activity AS (SELECT u.id,u.display_name,u.reputation,COUNT(p.id) AS post_count,COALESCE(SUM(p.score),0) AS total_score FROM users u LEFT JOIN posts p ON p.owner_user_id=u.id WHERE u.reputation>=1000 GROUP BY u.id,u.display_name,u.reputation) SELECT id,display_name,reputation,post_count,total_score,DENSE_RANK() OVER (ORDER BY total_score DESC) AS score_rank,DENSE_RANK() OVER (ORDER BY post_count DESC) AS activity_rank FROM user_activity ORDER BY score_rank LIMIT 100;",
}

var comments []string = []string{
	//Q01: Pełny klucz partycjonowania i join do posts oraz users
	"SELECT c.id,c.post_id,c.score,c.creation_date,c.comment_text,u.id AS commenter_id,u.display_name AS commenter_name,p.post_title,p.score AS post_score FROM comments c JOIN posts p ON p.id=c.post_id LEFT JOIN users u ON u.id=c.user_id WHERE c.id=9  AND c.post_id=47239;",
	//Q02: Tylko id, częściowe dopasowanie klucza KEY
	"SELECT c.id,c.post_id,c.score,c.creation_date,u.display_name,p.post_title FROM comments c JOIN posts p ON p.id=c.post_id LEFT JOIN users u ON u.id=c.user_id WHERE c.id=9;",
	//Q03: Tylko post_id, typowe zapytanie aplikacyjne bez pełnego klucza KEY
	"SELECT c.id,c.post_id,c.score,c.creation_date,u.display_name,p.post_title FROM comments c JOIN posts p ON p.id=c.post_id LEFT JOIN users u ON u.id=c.user_id WHERE c.post_id=456789 ORDER BY c.creation_date;",
	//Q04: Cztery pełne pary klucza przez alternatywy OR
	"SELECT c.id,c.post_id,c.score,c.creation_date,u.display_name,p.post_title FROM comments c JOIN posts p ON p.id=c.post_id LEFT JOIN users u ON u.id=c.user_id WHERE (c.id=9 AND c.post_id=47239) OR (c.id=12 AND c.post_id=47428) OR (c.id=25 AND c.post_id=47626) OR (c.id=1 AND c.post_id=35314) ORDER BY c.id;",
	//Q05: Zakres id i join do posts, przypadek kontrolny
	"SELECT c.id,c.post_id,c.score,c.creation_date,p.post_title,u.display_name FROM comments c JOIN posts p ON p.id=c.post_id LEFT JOIN users u ON u.id=c.user_id WHERE c.id>=10000000 AND c.id<10010000 ORDER BY c.id LIMIT 500;",
	//Q06: Filtrowanie po user_id bez warunku po kluczu partycjonowania
	"SELECT u.id,u.display_name,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.post_id) AS commented_posts,COALESCE(SUM(c.score),0) AS total_comment_score FROM comments c JOIN users u ON u.id=c.user_id WHERE c.user_id=1 GROUP BY u.id,u.display_name;",
	//Q07: Komentarze użytkownika z informacjami o postach
	"SELECT c.id,c.post_id,c.score,c.creation_date,p.post_title,p.post_type_id,p.score AS post_score,u.display_name FROM comments c JOIN posts p ON p.id=c.post_id JOIN users u ON u.id=c.user_id WHERE c.user_id=1 ORDER BY c.creation_date DESC LIMIT 100;",
	//Q08: Filtrowanie comments po dacie, brak pruning po KEY(id,post_id)
	"SELECT DATE(c.creation_date) AS day,COUNT(*) AS comment_count,COUNT(DISTINCT c.user_id) AS active_users,COUNT(DISTINCT c.post_id) AS commented_posts,AVG(c.score) AS avg_score FROM comments c WHERE c.creation_date>='2009-04-01' AND c.creation_date<'2009-07-01' GROUP BY DATE(c.creation_date) ORDER BY day;",
	//Q09: Komentarze do pytań z jednej partycji czasowej posts
	"SELECT p.id,p.post_title,p.score AS post_score,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.user_id) AS commenter_count,AVG(c.score) AS avg_comment_score FROM posts p JOIN comments c ON c.post_id=p.id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' AND p.post_type_id=1 GROUP BY p.id,p.post_title,p.score HAVING COUNT(c.id)>=5 ORDER BY comment_count DESC LIMIT 100;",
	//Q10: Ranking komentujących pytania z wybranego kwartału
	"SELECT u.id,u.display_name,u.reputation,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.post_id) AS commented_posts,COALESCE(SUM(c.score),0) AS total_comment_score FROM posts p JOIN comments c ON c.post_id=p.id JOIN users u ON u.id=c.user_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' AND p.post_type_id=1 GROUP BY u.id,u.display_name,u.reputation HAVING COUNT(c.id)>=3 ORDER BY comment_count DESC,total_comment_score DESC LIMIT 100;",
	//Q11: Autorzy postów i komentujący te posty
	"SELECT owner.id AS owner_id,owner.display_name AS owner_name,commenter.id AS commenter_id,commenter.display_name AS commenter_name,COUNT(c.id) AS comment_count,COUNT(DISTINCT p.id) AS post_count FROM posts p JOIN comments c ON c.post_id=p.id LEFT JOIN users owner ON owner.id=p.owner_user_id LEFT JOIN users commenter ON commenter.id=c.user_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' GROUP BY owner.id,owner.display_name,commenter.id,commenter.display_name HAVING COUNT(c.id)>=3 ORDER BY comment_count DESC LIMIT 100;",
	//Q12: Komentarze autora pod własnymi postami
	"SELECT u.id,u.display_name,COUNT(c.id) AS self_comment_count,COUNT(DISTINCT p.id) AS self_commented_posts FROM comments c JOIN posts p ON p.id=c.post_id JOIN users u ON u.id=c.user_id AND u.id=p.owner_user_id WHERE p.creation_date>='2009-01-01' AND p.creation_date<'2010-01-01' GROUP BY u.id,u.display_name ORDER BY self_comment_count DESC LIMIT 100;",
	//Q13: Najnowszy komentarz dla każdego postu z wybranego okresu
	"WITH ranked_comments AS (SELECT c.id,c.post_id,c.user_id,c.score,c.creation_date,ROW_NUMBER() OVER (PARTITION BY c.post_id ORDER BY c.creation_date DESC,c.id DESC) AS rn FROM comments c JOIN posts p ON p.id=c.post_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01') SELECT rc.id,rc.post_id,p.post_title,rc.score,rc.creation_date,u.display_name FROM ranked_comments rc JOIN posts p ON p.id=rc.post_id LEFT JOIN users u ON u.id=rc.user_id WHERE rc.rn=1 ORDER BY rc.creation_date DESC LIMIT 100;",
	//Q14: Ranking postów według liczby komentarzy z funkcją okienkową
	"WITH comment_stats AS (SELECT p.id,p.post_title,p.owner_user_id,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.user_id) AS commenter_count,AVG(c.score) AS avg_comment_score FROM posts p JOIN comments c ON c.post_id=p.id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' GROUP BY p.id,p.post_title,p.owner_user_id) SELECT cs.id,cs.post_title,u.display_name,cs.comment_count,cs.commenter_count,cs.avg_comment_score,DENSE_RANK() OVER (ORDER BY cs.comment_count DESC) AS comment_rank FROM comment_stats cs LEFT JOIN users u ON u.id=cs.owner_user_id ORDER BY comment_rank LIMIT 100;",
	//Q15: Komentarze do pytań i zaakceptowanych odpowiedziv
	"SELECT q.id AS question_id,q.post_title,a.id AS accepted_answer_id,COUNT(DISTINCT qc.id) AS question_comment_count,COUNT(DISTINCT ac.id) AS answer_comment_count,qu.display_name AS question_author,au.display_name AS answer_author FROM posts q JOIN posts a ON a.id=q.accepted_answer_id LEFT JOIN comments qc ON qc.post_id=q.id LEFT JOIN comments ac ON ac.post_id=a.id LEFT JOIN users qu ON qu.id=q.owner_user_id LEFT JOIN users au ON au.id=a.owner_user_id WHERE q.creation_date>='2009-04-01' AND q.creation_date<'2009-07-01' AND q.post_type_id=1 GROUP BY q.id,q.post_title,a.id,qu.display_name,au.display_name ORDER BY question_comment_count+answer_comment_count DESC LIMIT 100;",
	//Q16: Wybrane pełne klucze w CTE i join do posts oraz users
	"WITH selected_comments AS (SELECT id,post_id,user_id,score,creation_date FROM comments WHERE (id=9  AND post_id=47239) OR (id=12 AND post_id=47428) OR (id=25 AND post_id=47626) OR (id=1 AND post_id=35314)) SELECT sc.id,sc.post_id,sc.score,sc.creation_date,p.post_title,u.display_name FROM selected_comments sc JOIN posts p ON p.id=sc.post_id LEFT JOIN users u ON u.id=sc.user_id ORDER BY sc.id;",
	//Q17: Statystyki komentarzy oraz historii dla wybranych postów
	"WITH selected_posts AS (SELECT DISTINCT c.post_id FROM comments c WHERE (c.id=9 AND c.post_id=47239) OR (c.id=12 AND c.post_id=47428) OR (c.id=25 AND c.post_id=47626) OR (c.id=1 AND c.post_id=35314)),comment_stats AS (SELECT c.post_id,COUNT(*) AS comment_count,COUNT(DISTINCT c.user_id) AS commenter_count FROM comments c JOIN selected_posts sp ON sp.post_id=c.post_id GROUP BY c.post_id),history_stats AS (SELECT ph.post_id,COUNT(*) AS revision_count,COUNT(DISTINCT ph.user_id) AS editor_count FROM post_history ph JOIN selected_posts sp ON sp.post_id=ph.post_id GROUP BY ph.post_id) SELECT p.id,p.post_title,cs.comment_count,cs.commenter_count,hs.revision_count,hs.editor_count FROM selected_posts sp JOIN posts p ON p.id=sp.post_id LEFT JOIN comment_stats cs ON cs.post_id=sp.post_id LEFT JOIN history_stats hs ON hs.post_id=sp.post_id;",
	//Q18: Statystyki komentarzy oraz głosów dla wybranych postów
	"WITH selected_posts AS (SELECT DISTINCT c.post_id FROM comments c WHERE (c.id=9 AND c.post_id=47239) OR (c.id=12 AND c.post_id=47428) OR (c.id=25 AND c.post_id=47626) OR (c.id=1 AND c.post_id=35314)),comment_stats AS (SELECT c.post_id,COUNT(*) AS comment_count,SUM(c.score) AS comment_score FROM comments c JOIN selected_posts sp ON sp.post_id=c.post_id GROUP BY c.post_id),vote_stats AS (SELECT v.post_id,COUNT(*) AS vote_count,COUNT(DISTINCT v.vote_type_id) AS vote_type_count FROM votes v JOIN selected_posts sp ON sp.post_id=v.post_id GROUP BY v.post_id) SELECT p.id,p.post_title,cs.comment_count,cs.comment_score,vs.vote_count,vs.vote_type_count FROM selected_posts sp JOIN posts p ON p.id=sp.post_id LEFT JOIN comment_stats cs ON cs.post_id=sp.post_id LEFT JOIN vote_stats vs ON vs.post_id=sp.post_id;",
	//Q19: Miesięczne statystyki komentarzy według typu postu
	"SELECT YEAR(c.creation_date) AS year_number,MONTH(c.creation_date) AS month_number,p.post_type_id,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.user_id) AS active_commenters,COUNT(DISTINCT c.post_id) AS commented_posts,AVG(c.score) AS avg_comment_score FROM comments c JOIN posts p ON p.id=c.post_id WHERE c.creation_date>='2009-01-01' AND c.creation_date<'2010-01-01' GROUP BY YEAR(c.creation_date),MONTH(c.creation_date),p.post_type_id ORDER BY year_number,month_number,p.post_type_id;",
	//Q20: Pełny przypadek kontrolny bez predykatu po id ani post_id
	"SELECT u.id,u.display_name,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.post_id) AS commented_posts,COALESCE(SUM(c.score),0) AS total_comment_score,AVG(c.score) AS avg_comment_score FROM comments c JOIN users u ON u.id=c.user_id GROUP BY u.id,u.display_name HAVING COUNT(c.id)>=10 ORDER BY comment_count DESC LIMIT 100;",
}

var postH = []string{
	// Q01: Pełny klucz partycjonowania z partycji p0 oraz join do posts i users
	"SELECT ph.id,ph.post_id,ph.post_history_type_id,ph.creation_date,ph.revision_guid,p.post_title,p.score,u.id AS editor_id,u.display_name AS editor_name FROM post_history ph JOIN posts p ON p.id=ph.post_id LEFT JOIN users u ON u.id=ph.user_id WHERE ph.id=1894 AND ph.post_id=1679;",

	// Q02: Warunek tylko po id rekordu znajdującego się w p0
	"SELECT ph.id,ph.post_id,ph.post_history_type_id,ph.creation_date,p.post_title,u.display_name FROM post_history ph JOIN posts p ON p.id=ph.post_id LEFT JOIN users u ON u.id=ph.user_id WHERE ph.id=1894;",

	// Q03: Warunek tylko po post_id, bez pełnego klucza KEY
	"SELECT ph.id,ph.post_id,ph.post_history_type_id,ph.creation_date,ph.user_id,u.display_name,p.post_title FROM post_history ph JOIN posts p ON p.id=ph.post_id LEFT JOIN users u ON u.id=ph.user_id WHERE ph.post_id=1679 ORDER BY ph.creation_date DESC;",

	// Q04: Cztery pełne pary pochodzące z partycji p0, p1, p2 i p3
	"SELECT ph.id,ph.post_id,ph.post_history_type_id,ph.creation_date,p.post_title,u.display_name FROM post_history ph JOIN posts p ON p.id=ph.post_id LEFT JOIN users u ON u.id=ph.user_id WHERE (ph.id=1894 AND ph.post_id=1679) OR (ph.id=1418 AND ph.post_id=1240) OR (ph.id=2990 AND ph.post_id=2605) OR (ph.id=2671 AND ph.post_id=2332) ORDER BY ph.id;",

	// Q05: Zakres obejmujący rzeczywiście istniejące identyfikatory
	"SELECT ph.id,ph.post_id,ph.post_history_type_id,ph.creation_date,p.post_title,u.display_name FROM post_history ph JOIN posts p ON p.id=ph.post_id LEFT JOIN users u ON u.id=ph.user_id WHERE ph.id>=1400 AND ph.id<3001 ORDER BY ph.id LIMIT 500;",

	// Q06: Historia zmian wykonanych przez jednego użytkownika
	"SELECT u.id,u.display_name,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.post_id) AS edited_posts,COUNT(DISTINCT ph.post_history_type_id) AS history_type_count,MIN(ph.creation_date) AS first_revision,MAX(ph.creation_date) AS last_revision FROM post_history ph JOIN users u ON u.id=ph.user_id WHERE ph.user_id=1 GROUP BY u.id,u.display_name;",

	// Q07: Historia istniejącego postu według typu zmiany
	"SELECT p.id,p.post_title,ph.post_history_type_id,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.user_id) AS editor_count,MIN(ph.creation_date) AS first_revision,MAX(ph.creation_date) AS last_revision FROM post_history ph JOIN posts p ON p.id=ph.post_id WHERE ph.post_id=1679 GROUP BY p.id,p.post_title,ph.post_history_type_id ORDER BY revision_count DESC;",

	// Q08: Filtrowanie po creation_date bez warunku po kluczu partycjonowania
	"SELECT DATE(ph.creation_date) AS revision_day,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.post_id) AS edited_posts,COUNT(DISTINCT ph.user_id) AS active_editors FROM post_history ph WHERE ph.creation_date>='2009-04-01' AND ph.creation_date<'2009-07-01' GROUP BY DATE(ph.creation_date) ORDER BY revision_day;",

	// Q09: Statystyki historii pytań utworzonych w jednym kwartale
	"SELECT p.id,p.post_title,p.score,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.user_id) AS editor_count,COUNT(DISTINCT ph.post_history_type_id) AS history_type_count,MAX(ph.creation_date) AS last_revision FROM posts p JOIN post_history ph ON ph.post_id=p.id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' AND p.post_type_id=1 GROUP BY p.id,p.post_title,p.score HAVING COUNT(ph.id)>=2 ORDER BY revision_count DESC LIMIT 100;",

	// Q10: Ranking użytkowników edytujących posty z wybranego kwartału
	"SELECT u.id,u.display_name,u.reputation,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.post_id) AS edited_posts,COUNT(DISTINCT ph.post_history_type_id) AS history_type_count FROM posts p JOIN post_history ph ON ph.post_id=p.id JOIN users u ON u.id=ph.user_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' GROUP BY u.id,u.display_name,u.reputation HAVING COUNT(ph.id)>=3 ORDER BY revision_count DESC,edited_posts DESC LIMIT 100;",

	// Q11: Właściciele postów i użytkownicy edytujący ich posty
	"SELECT owner.id AS owner_id,owner.display_name AS owner_name,editor.id AS editor_id,editor.display_name AS editor_name,COUNT(ph.id) AS revision_count,COUNT(DISTINCT p.id) AS edited_posts FROM posts p JOIN post_history ph ON ph.post_id=p.id LEFT JOIN users owner ON owner.id=p.owner_user_id LEFT JOIN users editor ON editor.id=ph.user_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' GROUP BY owner.id,owner.display_name,editor.id,editor.display_name HAVING COUNT(ph.id)>=3 ORDER BY revision_count DESC LIMIT 100;",

	// Q12: Użytkownicy edytujący własne posty
	"SELECT u.id,u.display_name,COUNT(ph.id) AS own_revision_count,COUNT(DISTINCT p.id) AS own_edited_posts,COUNT(DISTINCT ph.post_history_type_id) AS history_type_count FROM posts p JOIN post_history ph ON ph.post_id=p.id AND ph.user_id=p.owner_user_id JOIN users u ON u.id=p.owner_user_id WHERE p.creation_date>='2009-01-01' AND p.creation_date<'2010-01-01' GROUP BY u.id,u.display_name ORDER BY own_revision_count DESC LIMIT 100;",

	// Q13: Najnowszy wpis historii dla każdego postu
	"WITH ranked_history AS (SELECT ph.id,ph.post_id,ph.user_id,ph.post_history_type_id,ph.creation_date,ROW_NUMBER() OVER (PARTITION BY ph.post_id ORDER BY ph.creation_date DESC,ph.id DESC) AS rn FROM post_history ph JOIN posts p ON p.id=ph.post_id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01') SELECT rh.id,rh.post_id,p.post_title,rh.post_history_type_id,rh.creation_date,u.display_name FROM ranked_history rh JOIN posts p ON p.id=rh.post_id LEFT JOIN users u ON u.id=rh.user_id WHERE rh.rn=1 ORDER BY rh.creation_date DESC LIMIT 100;",

	// Q14: Ranking postów według liczby zmian
	"WITH history_stats AS (SELECT p.id,p.post_title,p.owner_user_id,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.user_id) AS editor_count,COUNT(DISTINCT ph.post_history_type_id) AS history_type_count FROM posts p JOIN post_history ph ON ph.post_id=p.id WHERE p.creation_date>='2009-04-01' AND p.creation_date<'2009-07-01' GROUP BY p.id,p.post_title,p.owner_user_id) SELECT hs.id,hs.post_title,u.display_name,hs.revision_count,hs.editor_count,hs.history_type_count,DENSE_RANK() OVER (ORDER BY hs.revision_count DESC) AS revision_rank FROM history_stats hs LEFT JOIN users u ON u.id=hs.owner_user_id ORDER BY revision_rank LIMIT 100;",

	// Q15: Historia pytań i zaakceptowanych odpowiedzi
	"WITH question_history AS (SELECT ph.post_id,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.user_id) AS editor_count FROM post_history ph GROUP BY ph.post_id),answer_history AS (SELECT ph.post_id,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.user_id) AS editor_count FROM post_history ph GROUP BY ph.post_id) SELECT q.id AS question_id,q.post_title,a.id AS answer_id,qh.revision_count AS question_revisions,qh.editor_count AS question_editors,ah.revision_count AS answer_revisions,ah.editor_count AS answer_editors FROM posts q JOIN posts a ON a.id=q.accepted_answer_id LEFT JOIN question_history qh ON qh.post_id=q.id LEFT JOIN answer_history ah ON ah.post_id=a.id WHERE q.creation_date>='2009-04-01' AND q.creation_date<'2009-07-01' AND q.post_type_id=1 ORDER BY COALESCE(qh.revision_count,0)+COALESCE(ah.revision_count,0) DESC LIMIT 100;",

	// Q16: Pełne klucze ze wszystkich ośmiu partycji wybrane w CTE
	"WITH selected_history AS (SELECT id,post_id,user_id,post_history_type_id,creation_date FROM post_history WHERE (id=1894 AND post_id=1679) OR (id=1418 AND post_id=1240) OR (id=2990 AND post_id=2605) OR (id=2671 AND post_id=2332) OR (id=2620 AND post_id=2298) OR (id=1427 AND post_id=1265) OR (id=2497 AND post_id=2183) OR (id=1661 AND post_id=1474)) SELECT sh.id,sh.post_id,sh.post_history_type_id,sh.creation_date,p.post_title,p.score,u.display_name FROM selected_history sh JOIN posts p ON p.id=sh.post_id LEFT JOIN users u ON u.id=sh.user_id ORDER BY sh.id;",
	// Q17: Historia oraz komentarze dla czterech wskazanych postów
	"WITH selected_posts AS (SELECT DISTINCT ph.post_id FROM post_history ph WHERE (ph.id=1894 AND ph.post_id=1679) OR (ph.id=1418 AND ph.post_id=1240) OR (ph.id=2990 AND ph.post_id=2605) OR (ph.id=2671 AND ph.post_id=2332)),history_stats AS (SELECT ph.post_id,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.user_id) AS editor_count FROM post_history ph JOIN selected_posts sp ON sp.post_id=ph.post_id GROUP BY ph.post_id),comment_stats AS (SELECT c.post_id,COUNT(c.id) AS comment_count,COUNT(DISTINCT c.user_id) AS commenter_count FROM comments c JOIN selected_posts sp ON sp.post_id=c.post_id GROUP BY c.post_id) SELECT p.id,p.post_title,hs.revision_count,hs.editor_count,cs.comment_count,cs.commenter_count FROM selected_posts sp JOIN posts p ON p.id=sp.post_id LEFT JOIN history_stats hs ON hs.post_id=sp.post_id LEFT JOIN comment_stats cs ON cs.post_id=sp.post_id;",

	// Q18: Historia oraz głosy dla postów wskazanych rekordami ze wszystkich ośmiu partycji
	"WITH selected_posts AS (SELECT DISTINCT ph.post_id FROM post_history ph WHERE (ph.id=1894 AND ph.post_id=1679) OR (ph.id=1418 AND ph.post_id=1240) OR (ph.id=2990 AND ph.post_id=2605) OR (ph.id=2671 AND ph.post_id=2332) OR (ph.id=2620 AND ph.post_id=2298) OR (ph.id=1427 AND ph.post_id=1265) OR (ph.id=2497 AND ph.post_id=2183) OR (ph.id=1661 AND ph.post_id=1474)),history_stats AS (SELECT ph.post_id,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.post_history_type_id) AS history_type_count FROM post_history ph JOIN selected_posts sp ON sp.post_id=ph.post_id GROUP BY ph.post_id),vote_stats AS (SELECT v.post_id,COUNT(v.id) AS vote_count,COUNT(DISTINCT v.vote_type_id) AS vote_type_count FROM votes v JOIN selected_posts sp ON sp.post_id=v.post_id GROUP BY v.post_id) SELECT p.id,p.post_title,hs.revision_count,hs.history_type_count,vs.vote_count,vs.vote_type_count FROM selected_posts sp JOIN posts p ON p.id=sp.post_id LEFT JOIN history_stats hs ON hs.post_id=sp.post_id LEFT JOIN vote_stats vs ON vs.post_id=sp.post_id ORDER BY p.id;",

	// Q19: Miesięczne statystyki historii według typu postu i zmiany
	"SELECT YEAR(ph.creation_date) AS year_number,MONTH(ph.creation_date) AS month_number,p.post_type_id,ph.post_history_type_id,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.post_id) AS edited_posts,COUNT(DISTINCT ph.user_id) AS active_editors FROM post_history ph JOIN posts p ON p.id=ph.post_id WHERE ph.creation_date>='2009-01-01' AND ph.creation_date<'2010-01-01' GROUP BY YEAR(ph.creation_date),MONTH(ph.creation_date),p.post_type_id,ph.post_history_type_id ORDER BY year_number,month_number,p.post_type_id,ph.post_history_type_id;",

	// Q20: Przypadek kontrolny bez predykatu po id ani post_id
	"SELECT u.id,u.display_name,COUNT(ph.id) AS revision_count,COUNT(DISTINCT ph.post_id) AS edited_posts,COUNT(DISTINCT ph.post_history_type_id) AS history_type_count,MIN(ph.creation_date) AS first_revision,MAX(ph.creation_date) AS last_revision FROM post_history ph JOIN users u ON u.id=ph.user_id GROUP BY u.id,u.display_name HAVING COUNT(ph.id)>=10 ORDER BY revision_count DESC LIMIT 100;",
}
