{
 "title": "Partycjonowanie baz danych i ich wpływ na wydajność i skalowalność aplikacji",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "mysqlhost",
    "query": {
     "query": "label_values(mysql_up,instance)"
    }
   },
   {
    "name": "nodehost",
    "query": {
     "query": "label_values(node_arp_entries,instance)"
    }
   },
   {
    "name": "storageDevice",
    "query": {
     "query": "label_values(node_disk_read_time_seconds_total,device)"
    }
   },
   { "name": "test_id", "query": "Select id from Tests;" }
  ]
 },
 "panels": [
  { "title": "All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Testy",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "targets": [
    { "dataset": "logdb", "rawSql": "Select * from Tests;" }
   ]
  },
  {
   "title": "Test info",
   "type": "table",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "dataset": "logdb",
     "rawSql": "WITH test_bounds AS (\n    SELECT\n        timeStart,\n        timeEnd,\n        TIMESTAMPDIFF(MICROSECOND, timeStart, timeEnd) / 1000000.0\n            AS test_duration_s\n    FROM Tests\n    WHERE id = ${test_id}\n),\nranked AS (\n    SELECT\n        q.duration_ms,\n        CUME_DIST() OVER (ORDER BY q.duration_ms) AS cumulative_distribution\n    FROM QueryResults AS q\n    CROSS JOIN test_bounds AS tb\n    WHERE q.timeEnded >= tb.timeStart\n      AND q.timeEnded < tb.timeEnd\n      AND q.duration_ms IS NOT NULL\n)\nSELECT\n    COUNT(*) AS `Liczba zapytań`,\n    ROUND(\n        COUNT(*) / NULLIF(MAX(tb.test_duration_s), 0),\n        3\n    ) AS `Średnie QPS`,\n    MIN(\n        CASE\n            WHEN cumulative_distribution >= 0.50\n            THEN duration_ms\n        END\n    ) AS `P50 [ms]`,\n    MIN(\n        CASE\n            WHEN cumulative_distribution >= 0.95\n            THEN duration_ms\n        END\n    ) AS `P95 [ms]`,\n    MIN(\n        CASE\n            WHEN cumulative_distribution >= 0.99\n            THEN duration_ms\n        END\n    ) AS `P99 [ms]`\nFROM ranked\nCROSS JOIN test_bounds AS tb;"
    }
   ]
  },
  {
   "title": "CPU średnia",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  avg(\n    increase(\n      node_cpu_seconds_total{\n        instance=\"$nodehost\",\n        mode=\"idle\"\n      }[$__range]\n    )\n  ) / $__range_s\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dysk Odczyt śrdeni MiB/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    node_disk_read_bytes_total{\n      instance=\"$nodehost\",\n      device=\"$storageDevice\"\n    }[$__range]\n  )\n) / $__range_s / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dysk Zapis MiB/S",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    node_disk_written_bytes_total{\n      instance=\"$nodehost\",\n      device=\"$storageDevice\"\n    }[$__range]\n  )\n) / $__range_s / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS obecnie",
   "type": "stat",
   "description": "**QPS w tym momęcie**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$mysqlhost\"}[5m])"
    }
   ]
  },
  {
   "title": "Czas przetwarzania",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "logdb",
     "rawSql": "WITH test_bounds AS (\n    SELECT\n        timeStart,\n        timeEnd\n    FROM Tests\n    WHERE id = $test_id \n),\nbucketed AS (\n    SELECT\n        $__timeGroup(q.timeEnded, '$__interval') AS time_bucket,\n        q.duration_ms\n    FROM QueryResults AS q\n    CROSS JOIN test_bounds AS tb\n    WHERE q.timeEnded >= tb.timeStart\n      AND q.timeEnded < tb.timeEnd\n      AND q.duration_ms IS NOT NULL\n),\nranked AS (\n    SELECT\n        time_bucket,\n        duration_ms,\n        CUME_DIST() OVER (\n            PARTITION BY time_bucket\n            ORDER BY duration_ms\n        ) AS cumulative_distribution\n    FROM bucketed\n)\nSELECT\n    FROM_UNIXTIME(time_bucket) AS time,\n    ROUND(AVG(duration_ms), 3) AS avg_ms,\n    MIN(\n        CASE\n            WHEN cumulative_distribution >= 0.50\n            THEN duration_ms\n        END\n    ) AS p50_ms,\n    MIN(\n        CASE\n            WHEN cumulative_distribution >= 0.95\n            THEN duration_ms\n        END\n    ) AS p95_ms,\n    MIN(\n        CASE\n            WHEN cumulative_distribution >= 0.99\n            THEN duration_ms\n        END\n    ) AS p99_ms\nFROM ranked\nGROUP BY time_bucket\nORDER BY time_bucket;"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dataset": "logdb",
     "rawSql": "WITH test_bounds AS (\n    SELECT\n        timeStart,\n        timeEnd\n    FROM Tests\n    WHERE id = $test_id\n),\nbucketed AS (\n    SELECT\n        $__timeGroup(q.timeEnded, '$__interval') AS time_bucket,\n        COUNT(*) AS query_count\n    FROM QueryResults AS q\n    CROSS JOIN test_bounds AS tb\n    WHERE q.timeEnded >= tb.timeStart\n      AND q.timeEnded < tb.timeEnd\n    GROUP BY 1\n)\nSELECT\n    FROM_UNIXTIME(time_bucket) AS time,\n    ROUND(\n        query_count / NULLIF($__interval_ms / 1000.0, 0),\n        3\n    ) AS throughput_qps\nFROM bucketed\nORDER BY time_bucket;"
    }
   ]
  },
  {
   "title": "Dysk MiB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    node_disk_read_bytes_total{\n      instance=\"$nodehost\",\n      device=\"$storageDevice\"\n    }[$__range]\n  )\n) / $__range_s / 1024 / 1024",
     "legendFormat": "Odczyt"
    },
    {
     "expr": "sum(\n  increase(\n    node_disk_written_bytes_total{\n      instance=\"$nodehost\",\n      device=\"$storageDevice\"\n    }[$__range]\n  )\n) / $__range_s / 1024 / 1024",
     "legendFormat": "Zapis"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  avg by (instance) (\n    increase(\n      node_cpu_seconds_total{\n        mode=\"idle\"\n      }[$__range]\n    ) / $__range_s\n  )\n)",
     "legendFormat": "Użycie CPU"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "QPS dla interwału $interval"
    }
   ]
  },
  {
   "title": "Użycie sieci przez $interval albo 1m - MySQL ",
   "type": "timeseries",
   "description": "**MySQL Network Usage Hourly**\n\nHere we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_received{instance=\"$mysqlhost\"}[$interval]) or increase(mysql_global_status_bytes_received{instance=\"$mysqlhost\"}[1m])",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_sent{instance=\"$mysqlhost\"}[$interval]) or increase(mysql_global_status_bytes_sent{instance=\"$mysqlhost\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Aktywne wątki klientów MySQL",
   "type": "timeseries",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$mysqlhost\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Szczytowa liczba połączonych wątków"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$mysqlhost\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Szczytowa liczba działających wątków"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{instance=\"$mysqlhost\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Średnia liczba działających wątków"
    },
    {
     "expr": "mysql_global_status_threads_connected{instance=\"$mysqlhost\"}",
     "legendFormat": "Połączone wątki"
    },
    {
     "expr": "mysql_global_status_threads_running{instance=\"$mysqlhost\"}",
     "legendFormat": "Działające wątki"
    }
   ]
  },
  {
   "title": "Ruch sieciowy MySQL",
   "type": "timeseries",
   "description": "**Ruch sieciowy MySQL**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Przychodzące"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Wychodzące"
    }
   ]
  },
  {
   "title": " Wykorzystanie/obciążenie procesora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$nodehost\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$nodehost\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_seconds_total_average{instance=~\"$nodehost\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_seconds_total_average{instance=~\"$nodehost\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$nodehost\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$nodehost\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) ))*100,100)",
     "legendFormat": "Maksymalne wykorzystanie rdzenia"
    },
    {
     "expr": "node_load1{instance=\"$nodehost\"}",
     "legendFormat": "Obciąrzenie 1m"
    }
   ]
  },
  {
   "title": "Opóźnienie Dysku",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum((rate(node_disk_read_time_seconds_total{device=\"$storageDevice\", instance=\"$nodehost\"}[$interval]) / rate(node_disk_reads_completed_total{device=\"$storageDevice\", instance=\"$nodehost\"}[$interval])) or (irate(node_disk_read_time_seconds_total{device=\"$storageDevice\", instance=\"$nodehost\"}[5m]) / irate(node_disk_reads_completed_total{device=\"$storageDevice\", instance=\"$nodehost\"}[5m]))\nor avg_over_time(aws_rds_read_latency_average{instance=\"$nodehost\"}[$interval]) or avg_over_time(aws_rds_read_latency_average{instance=\"$nodehost\"}[5m]))",
     "legendFormat": "Odczyt"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum((rate(node_disk_write_time_seconds_total{device=\"$storageDevice\", instance=\"$nodehost\"}[$interval]) / rate(node_disk_writes_completed_total{device=\"$storageDevice\", instance=\"$nodehost\"}[$interval])) or (irate(node_disk_write_time_seconds_total{device=\"$storageDevice\", instance=\"$nodehost\"}[5m]) / irate(node_disk_writes_completed_total{device=\"$storageDevice\", instance=\"$nodehost\"}[5m])) or \navg_over_time(aws_rds_write_latency_average{instance=\"$nodehost\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=\"$nodehost\"}[5m]))",
     "legendFormat": "Zapis"
    }
   ]
  },
  {
   "title": "Aktywnośc wejścia/wyjścia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{instance=\"$nodehost\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$nodehost\"}[5m]) * 1024",
     "legendFormat": "Zapis"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{instance=\"$nodehost\" }[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$nodehost\"}[5m]) * 1024",
     "legendFormat": "Odczyt"
    }
   ]
  },
  {
   "title": "Ruch sieciowy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$nodehost\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{instance=\"$nodehost\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$nodehost\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$nodehost\"}[5m])) ",
     "legendFormat": "Odbieranie"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$nodehost\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{instance=\"$nodehost\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$nodehost\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=\"$nodehost\"}[5m]))",
     "legendFormat": "Wysyłanie"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{instance=\"$nodehost\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$nodehost\"}[5m]) * 4096",
     "legendFormat": "Swap In (Odczyt)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{instance=\"$nodehost\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$nodehost\"}[5m]) * 4096",
     "legendFormat": "Swap Out (Zapis)"
    }
   ]
  },
  {
   "title": "MySQL Questions",
   "type": "timeseries",
   "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_questions{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Questions"
    }
   ]
  },
  {
   "title": "Licznik Poleceń",
   "type": "timeseries",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$mysqlhost\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"$mysqlhost\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "timeseries",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$mysqlhost\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$mysqlhost\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$mysqlhost\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$mysqlhost\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "timeseries",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_slow_queries{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  {
   "title": "MySQL Sorts",
   "type": "timeseries",
   "description": "**MySQL Sorts**\n\nDue to a query's structure, order, or other requirements, MySQL sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, MySQL then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_rows{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_sort_rows{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Sort Rows"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_range{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_sort_range{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Sort Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_merge_passes{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_sort_merge_passes{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Sort Merge Passes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_scan{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_sort_scan{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Sort Scan"
    }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "timeseries",
   "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_join{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_select_full_join{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Select Full Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_range_join{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_select_full_range_join{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_select_range{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Select Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range_check{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_select_range_check{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Select Range Check"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_scan{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_select_scan{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Select Scan"
    }
   ]
  },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "timeseries",
   "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 11, "w": 7, "x": 5, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_tables{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_opened_tables{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_table_open_cache_overflows{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$mysqlhost\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$mysqlhost\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$mysqlhost\"}[5m])))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "timeseries",
   "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
   "gridPos": { "h": 11, "w": 5, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_immediate{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_table_locks_immediate{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Table Locks Immediate"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_waited{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_table_locks_waited{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Table Locks Waited"
    }
   ]
  },
  {
   "title": "MySQL File Openings",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_files{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_opened_files{instance=\"$mysqlhost\"}[5m])",
     "legendFormat": "Openings"
    }
   ]
  },
  {
   "title": "Inne",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Przegląd pamięci wewnętrznej MySQL ",
     "type": "timeseries",
     "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool,  TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$nodehost\"}",
       "legendFormat": "Pamięć systemowa"
      },
      {
       "expr": "mysql_global_status_innodb_page_size{instance=\"$mysqlhost\"} * on (instance) mysql_global_status_buffer_pool_pages{instance=\"$mysqlhost\",state=\"data\"}",
       "legendFormat": "Dane przechowywane w buforze InnoDB"
      },
      {
       "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\"$mysqlhost\"}",
       "legendFormat": "Rozbiar bufora dziennkika InnoDB"
      },
      {
       "expr": "mysql_global_variables_innodb_additional_mem_pool_size{instance=\"$mysqlhost\"}",
       "legendFormat": "Rozmiar dodatkowej puli pamięci InnoDB - starawersjaMysql"
      },
      {
       "expr": "mysql_global_status_innodb_mem_dictionary{instance=\"$mysqlhost\"}",
       "legendFormat": "Rozmiar słownika danych InnoDB"
      },
      {
       "expr": "mysql_global_variables_key_buffer_size{instance=\"$mysqlhost\"}",
       "legendFormat": "Rozmiar bufora indeksów - myISAM"
      },
      {
       "expr": "mysql_global_variables_query_cache_size{instance=\"$mysqlhost\"}",
       "legendFormat": "Rozmiar cache zapytań"
      },
      {
       "expr": "mysql_global_status_innodb_mem_adaptive_hash{instance=\"$mysqlhost\"}",
       "legendFormat": "Rozmiar adaptacyjnego indeksu haszującego"
      }
     ]
    },
    {
     "title": "Zajętość pamięci RAM przez bufor InnoDb",
     "type": "stat",
     "description": "**InnoDB Buffer Pool Size % of Total RAM**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(mysql_global_variables_innodb_buffer_pool_size{instance=\"$mysqlhost\"})*100/scalar(node_memory_MemTotal_bytes{instance=\"$nodehost\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Size",
     "type": "stat",
     "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
     "gridPos": { "h": 9, "w": 3, "x": 10, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$mysqlhost\"}"
      }
     ]
    },
    {
     "title": "MySQL Open Files",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 13, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_open_files{instance=\"$mysqlhost\"}",
       "legendFormat": "Open Files"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_open_files_limit{instance=\"$mysqlhost\"}",
       "legendFormat": "Open Files Limit"
      },
      {
       "expr": "mysql_global_status_innodb_num_open_files{instance=\"$mysqlhost\"}",
       "legendFormat": "InnoDB Open Files"
      }
     ]
    },
    {
     "title": "Porzucone połączenia MySQL",
     "type": "timeseries",
     "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
     "gridPos": { "h": 9, "w": 5, "x": 17, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_connects{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_aborted_connects{instance=\"$mysqlhost\"}[5m])",
       "legendFormat": "Porzucone połączenia (attempts)"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_clients{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_aborted_clients{instance=\"$mysqlhost\"}[5m])",
       "legendFormat": "Porzucone połączenia (timeout)"
      }
     ]
    },
    {
     "title": "Połączenia MySQL",
     "type": "timeseries",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$mysqlhost\"}[$interval])  or mysql_global_status_threads_connected{instance=\"$mysqlhost\"} )",
       "legendFormat": "Połączenia"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_max_used_connections{instance=\"$mysqlhost\"}",
       "legendFormat": "Maksymalna liczba połączeń użytych połączeń"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_max_connections{instance=\"$mysqlhost\"}",
       "legendFormat": "Maxymalna liczba połączeń"
      }
     ]
    },
    {
     "title": "Memory Distribution",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 3, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemTotal_bytes{instance=\"$nodehost\"} - (node_memory_MemFree_bytes{instance=\"$nodehost\"} + node_memory_Buffers_bytes{instance=\"$nodehost\"} + node_memory_Cached_bytes{instance=\"$nodehost\"})",
       "legendFormat": "Użyta"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemFree_bytes{instance=\"$nodehost\"}",
       "legendFormat": "Wolna"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_Buffers_bytes{instance=\"$nodehost\"}",
       "legendFormat": "Bofor"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_Cached_bytes{instance=\"$nodehost\"}",
       "legendFormat": "Cached"
      }
     ]
    },
    {
     "title": "MySQL Thread Cache",
     "type": "timeseries",
     "description": "**MySQL Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in MySQL 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_thread_cache_size{instance=\"$mysqlhost\"}",
       "legendFormat": "Thread Cache Size"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_threads_cached{instance=\"$mysqlhost\"}",
       "legendFormat": "Threads Cached"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_threads_created{instance=\"$mysqlhost\"}[$interval]) or irate(mysql_global_status_threads_created{instance=\"$mysqlhost\"}[5m])",
       "legendFormat": "Threads Created"
      }
     ]
    },
    {
     "title": "Top Command Counters Hourly",
     "type": "timeseries",
     "description": "**Top Command Counters Hourly**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 9, "w": 7, "x": 15, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, increase(mysql_global_status_commands_total{instance=\"$mysqlhost\"}[1h])>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    }
   ]
  }
 ]
}